#!/usr/bin/env bash

set -e

# Other Java options

JAVA_OPTS="$JAVA_OPTS -XX:+UseConcMarkSweepGC"
JAVA_OPTS="$JAVA_OPTS -Xms64m"
JAVA_OPTS="$JAVA_OPTS -Xmx64m"

echo "Using these JAVA_OPTS: ${JAVA_OPTS}"

exec java $JAVA_OPTS -jar ./PTNotifications.jar
